#
#  Database configuration information

database:
  variant: mysql # the type of database (mysql, postgres, oracle, etc)
  server: localhost # the hostname of the server
  port: 3306 # the port the db-server is listening
  username: root # username for user with write privileges
  password: admin # password of the user
  schema: documents # database schema whose tables will be accessed
  #
  # The JDBC information
  #
  jdbc:
    driver-class: com.mysql.cj.jdbc.Driver
    jar-file: mysql-connector-j-8.1.0.jar
    url-format: jdbc:mysql://{server}:{port}/{schema}

  postgresql:
    variant: postgresql
    server: localhost
    schema: postgres
    port: 5432
    username: praveen
    password: password
    jdbc:
      driver-class: org.postgresql.Driver
      jar-file: postgresql-42.2.5.jar
      url-format: jdbc:postgresql://{server}:{port}/{schema}

#
# Document source directory
#
documents:
  source-dir: /Users/praveen/dev/llm-bootcamp/Assignment1/data_files
  image-dir: /Volumes/MacX_1TB/devX/data/image/images/25kphotos_sample/

#
# Spark details
#
spark:
  spark-home: /Users/praveen/dev/apps/spark-3.5.0-bin-hadoop3
  python-path: /Users/praveen/dev/apps/anaconda3/envs/llama/bin/python

#
# Models
#
models:
  multilingual-sentence-encoder: distiluse-base-multilingual-cased-v2
  multilingual-cross-encoder: cross-encoder/stsb-distilroberta-base
  spacy-model: en_core_web_sm
  spacy-sentence-embedding-model: distiluse-base-multilingual-cased-v2
  device: cpu
  sentence-embedding:
    normalize-embeddings: True

text:
  chunk-size: 500
  chunk-similarity-threshold: 0.2

#
# Elastic-search
# es_home is used to locate cert path
# ca_cert = es_home + "/config/certs/http_ca.crt",

elasticsearch:
  index_name: documents
  password: =7So_6RkM4TyCfMQGmJx
  eshome: /Users/praveen/dev/docker/elasticsearch

#
# FAISS search
#

search:
  faiss:
    index_file: /Users/praveen/dev/llm-bootcamp/sv-release/faiss-index/faiss_index_file

#
# Services
#
services:
  es_index: https://localhost:9200
  search: http://localhost:8006/search

  # GPU heavy
  clean_chunk: http://localhost:8001/chunker
  sentence_vectorizer: http://localhost:8002/embedding
  faiss_index_builder: http://localhost:8003/faiss_index_builder
  faiss_search: http://localhost:8004/faiss_search
  reranker: http://localhost:8005/rerank
